# Generated by Django 4.2.25 on 2025-10-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaogrupo',
            name='funcao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alocacaogrupo',
            name='is_coordenador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='alocacaoministerio',
            index=models.Index(fields=['evento'], name='inscricoes__evento__359e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacaoministerio',
            index=models.Index(fields=['ministerio'], name='inscricoes__ministe_e636d5_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacaoministerio',
            index=models.Index(fields=['is_coordenador'], name='inscricoes__is_coor_8f299e_idx'),
        ),
    ]
