# Generated by Django 5.2.3 on 2025-08-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_marketing_opt_in', models.BooleanField(default=False, verbose_name='Aceita marketing no WhatsApp')),
                ('whatsapp_optin_data', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_optin_fonte', models.CharField(choices=[('form', 'Formulário/Portal'), ('admin', 'Admin'), ('import', 'Importação')], default='admin', max_length=20)),
                ('whatsapp_optin_prova', models.TextField(blank=True, help_text='Como foi coletado (ex.: checkbox marcado, IP, carimbo de data/hora, etc.)', null=True)),
                ('politica_versao', models.CharField(blank=True, max_length=20, null=True)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to='inscricoes.participante')),
            ],
        ),
    ]
