# Generated by Django 4.2.25 on 2025-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoacampamento',
            name='tipo',
            field=models.CharField(choices=[('senior', 'Acampamento Sênior'), ('juvenil', 'Acampamento Juvenil'), ('mirim', 'Acampamento Mirim'), ('servos', 'Acampamento de Servos'), ('casais', 'Encontro de Casais'), ('evento', 'Evento'), ('retiro', 'Retiro'), ('pagamento', 'Pagamento')], max_length=20),
        ),
    ]
