# Generated by Django 5.2.3 on 2025-08-31 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateField(default=django.utils.timezone.localdate)),
                ('publicado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='comunicados/capas/')),
            ],
            options={
                'ordering': ['-data_publicacao', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoComunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('visivel_site', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data_inicio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='leadlanding',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadlanding',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leadlanding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='leadlanding',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='leadlanding',
            index=models.Index(fields=['created_at'], name='inscricoes__created_584999_idx'),
        ),
        migrations.AddIndex(
            model_name='leadlanding',
            index=models.Index(fields=['email'], name='inscricoes__email_4374c6_idx'),
        ),
        migrations.AddIndex(
            model_name='leadlanding',
            index=models.Index(fields=['origem'], name='inscricoes__origem_bcada0_idx'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='paroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='inscricoes.paroquia'),
        ),
        migrations.AddField(
            model_name='eventocomunitario',
            name='paroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_comunidade', to='inscricoes.paroquia'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['created_at'], name='inscricoes__created_5b118a_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['path'], name='inscricoes__path_fee4d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventocomunitario',
            constraint=models.UniqueConstraint(fields=('paroquia', 'slug'), name='unique_evento_comunitario_por_paroquia'),
        ),
    ]
