# Generated by Django 5.2.3 on 2025-08-12 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paroquia',
            name='telefone',
            field=models.CharField(help_text='Telefone no formato E.164 BR: +55DDDNÚMERO (ex.: +5563920013103)', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use +55 seguido de 10 ou 11 dígitos (ex.: +5563920013103).', regex='^\\+55\\d{10,11}$')]),
        ),
    ]
