# Generated by Django 5.2.3 on 2025-08-12 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_alter_paroquia_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='telefone_contato',
            field=models.CharField(blank=True, help_text='Use +55DDDNÚMERO (ex.: +5563920013103)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use +55 seguido de 10 ou 11 dígitos (ex.: +5563920013103).', regex='^\\+55\\d{10,11}$')], verbose_name='Telefone de Contato (E.164 BR)'),
        ),
    ]
