# Generated by Django 4.2.25 on 2025-10-06 19:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_alocacaogrupo_funcao_alocacaogrupo_is_coordenador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricaocasais',
            name='foto_casal',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto do casal'),
        ),
    ]
