# Generated by Django 4.2.25 on 2025-10-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_alter_eventoacampamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaoministerio',
            name='is_coordenador',
            field=models.BooleanField(default=False, verbose_name='É coordenador(a) do ministério?'),
        ),
        migrations.AlterField(
            model_name='alocacaoministerio',
            name='inscricao',
            field=models.OneToOneField(help_text='A inscrição deste servo (no evento de Servos).', on_delete=django.db.models.deletion.CASCADE, related_name='alocacao_ministerio', to='inscricoes.inscricao'),
        ),
        migrations.AddConstraint(
            model_name='alocacaoministerio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_coordenador', True)), fields=('ministerio',), name='uniq_um_coordenador_por_ministerio'),
        ),
    ]
