# Generated by Django 4.2.25 on 2025-10-07 01:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_alter_inscricaocasais_foto_casal'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicaprivacidade',
            name='imagem_pagto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem do Pagamento (PIX / instruções)'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='foto_casal',
            field=models.ImageField(blank=True, null=True, upload_to='casais/fotos/', verbose_name='Foto do casal'),
        ),
    ]
