# Generated by Django 5.2.3 on 2025-08-12 12:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_alter_politicaprivacidade_telefone_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('permite_reembolso', models.BooleanField(default=True, help_text='Se desmarcado, o evento não aceitará solicitações de reembolso.')),
                ('prazo_solicitacao_dias', models.PositiveIntegerField(default=7, help_text='Quantos dias ANTES do início do evento o participante pode solicitar reembolso.')),
                ('taxa_administrativa_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual descontado no reembolso (0 a 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('descricao', models.TextField(blank=True, help_text='Texto exibido ao participante com os critérios de reembolso. Ex.: Reembolso integral até 7 dias antes; após isso, 70%.')),
                ('contato_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato_whatsapp', models.CharField(blank=True, help_text='WhatsApp em E.164 (ex.: +5563920013103).', max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(help_text='Cada evento pode ter (no máximo) uma política de reembolso.', on_delete=django.db.models.deletion.CASCADE, related_name='politica_reembolso', to='inscricoes.eventoacampamento')),
            ],
            options={
                'verbose_name': 'Política de Reembolso',
                'verbose_name_plural': 'Políticas de Reembolso',
            },
        ),
    ]
