# Generated by Django 4.2.25 on 2025-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_alocacaoministerio_is_coordenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviada'), ('under_review', 'Em análise'), ('approved', 'Aprovada'), ('waitlist', 'Lista de espera'), ('rejected', 'Rejeitada'), ('selected', 'Selecionada/Convocada'), ('pay_pending', 'Pagamento pendente'), ('pay_confirmed', 'Pagamento confirmado'), ('cancel_user', 'Cancelada pelo usuário'), ('cancel_admin', 'Cancelada pela paróquia'), ('refund_req', 'Reembolso solicitado'), ('refund_ok', 'Reembolso aprovado'), ('refund_den', 'Reembolso negado')], db_index=True, default='draft', max_length=32),
        ),
    ]
