# Generated by Django 5.2.3 on 2025-08-16 20:35

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_politicareembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicaprivacidade',
            name='imagem_ajuda',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem da Ajuda (botão flutuante)'),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='contato_whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp em E.164 (ex.: +5563920013103).', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Use +55 seguido de 10 ou 11 dígitos.', regex='^\\+55\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='descricao',
            field=models.TextField(blank=True, help_text='Detalhe as regras (ex.: Integral até 7 dias antes; após isso, 70%).'),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='prazo_solicitacao_dias',
            field=models.PositiveIntegerField(default=7, help_text='Dias ANTES do início do evento para solicitar reembolso.'),
        ),
        migrations.AlterField(
            model_name='preferenciascomunicacao',
            name='whatsapp_optin_prova',
            field=models.TextField(blank=True, help_text='Como foi coletado (ex.: checkbox, IP, data/hora)', null=True),
        ),
    ]
