# Generated by Django 4.2.25 on 2025-10-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_inscricao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacaoministerio',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='inscricoes.ministerio'),
        ),
    ]
