# Generated by Django 4.2.25 on 2025-10-09 16:14

import cloudinary.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_fix_alocacaogrupo_evento_e_ministerio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='taxa_credito_fixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='taxa_credito_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='taxa_debito_fixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='taxa_debito_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='taxa_pix_fixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor fixo por transação PIX', max_digits=8),
        ),
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='taxa_pix_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual sobre o valor do PIX (ex.: 0.99 para 0,99%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='politicaprivacidade',
            name='imagem_insc',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagem exibida nas telas de inscrição (opcional).', max_length=255, null=True, verbose_name='Imagem da Inscrição'),
        ),
        migrations.AlterField(
            model_name='mercadopagoconfig',
            name='access_token',
            field=models.CharField(max_length=255, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='mercadopagoconfig',
            name='public_key',
            field=models.CharField(max_length=255, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='mercadopagoconfig',
            name='sandbox_mode',
            field=models.BooleanField(default=True, verbose_name='Sandbox'),
        ),
    ]
