# Generated by Django 4.2.25 on 2025-10-10 00:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0006_mercadopagoconfig_taxa_credito_fixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadopagoownerconfig',
            name='chave_pix',
            field=models.CharField(default=1, max_length=140, verbose_name='Chave PIX do dono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadopagoownerconfig',
            name='cidade_recebedor',
            field=models.CharField(default='SAO PAULO', max_length=15, verbose_name='Cidade (recebedor PIX)'),
        ),
        migrations.AddField(
            model_name='mercadopagoownerconfig',
            name='nome_recebedor',
            field=models.CharField(default=1, max_length=25, verbose_name='Nome (recebedor PIX)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadopagoownerconfig',
            name='public_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Public Key'),
        ),
        migrations.AddField(
            model_name='paroquia',
            name='repasse_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Percentual aplicado por padrão sobre o líquido arrecadado.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual de Repasse ao Dono (%)'),
        ),
        migrations.AlterField(
            model_name='mercadopagoownerconfig',
            name='access_token',
            field=models.CharField(max_length=255, verbose_name='Access Token'),
        ),
    ]
