# Generated by Django 5.2.3 on 2025-08-17 23:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0006_inscricao_cpf_conjuge_inscricao_inscricao_pareada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoOwnerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(default='Admin do Sistema', max_length=100)),
                ('access_token', models.CharField(max_length=255)),
                ('notificacao_webhook_url', models.URLField(blank=True, help_text='Opcional: URL pública do webhook de repasses', null=True)),
                ('email_cobranca', models.EmailField(blank=True, help_text='E-mail que aparecerá como pagador padrão', max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração MP (Dono)',
                'verbose_name_plural': 'Configurações MP (Dono)',
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='fee_mp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='net_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('valor_repasse', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('transacao_id', models.CharField(blank=True, max_length=64, null=True)),
                ('qr_code_text', models.TextField(blank=True, null=True)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasses', to='inscricoes.eventoacampamento')),
                ('paroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasses', to='inscricoes.paroquia')),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pendente')), fields=('paroquia', 'evento', 'status'), name='uniq_repasse_pendente_por_evento')],
            },
        ),
    ]
