# Generated by Django 5.2.3 on 2025-08-18 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0007_mercadopagoownerconfig_pagamento_fee_mp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paroquia',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='status',
            field=models.CharField(blank=True, choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=10),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone no formato E.164 BR: +55DDDNÚMERO (ex.: +5563920013103)', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use +55 seguido de 10 ou 11 dígitos (ex.: +5563920013103).', regex='^\\+55\\d{10,11}$')]),
        ),
    ]
