# Generated by Django 5.2.3 on 2025-10-18 16:49

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0007_mercadopagoownerconfig_chave_pix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mercadopagoownerconfig',
            options={'verbose_name': 'ConfiguraÃ§Ã£o MP (Dono)', 'verbose_name_plural': 'ConfiguraÃ§Ãµes MP (Dono)'},
        ),
        migrations.AlterModelOptions(
            name='politicareembolso',
            options={'verbose_name': 'PolÃ\xadtica de Reembolso', 'verbose_name_plural': 'PolÃ\xadticas de Reembolso'},
        ),
        migrations.AddField(
            model_name='inscricaocasais',
            name='outra_paroquia',
            field=models.CharField(blank=True, help_text='Preencha se nÃ£o encontrou sua parÃ³quia na lista.', max_length=120, verbose_name='Outra parÃ³quia (texto livre)'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='outra_paroquia',
            field=models.CharField(blank=True, help_text='Preencha se nÃ£o encontrou sua parÃ³quia na lista.', max_length=120, verbose_name='Outra parÃ³quia (texto livre)'),
        ),
        migrations.AddField(
            model_name='inscricaojuvenil',
            name='outra_paroquia',
            field=models.CharField(blank=True, help_text='Preencha se nÃ£o encontrou sua parÃ³quia na lista.', max_length=120, verbose_name='Outra parÃ³quia (texto livre)'),
        ),
        migrations.AddField(
            model_name='inscricaomirim',
            name='outra_paroquia',
            field=models.CharField(blank=True, help_text='Preencha se nÃ£o encontrou sua parÃ³quia na lista.', max_length=120, verbose_name='Outra parÃ³quia (texto livre)'),
        ),
        migrations.AddField(
            model_name='inscricaoretiro',
            name='outra_paroquia',
            field=models.CharField(blank=True, help_text='Preencha se nÃ£o encontrou sua parÃ³quia na lista.', max_length=120, verbose_name='Outra parÃ³quia (texto livre)'),
        ),
        migrations.AddField(
            model_name='inscricaosenior',
            name='outra_paroquia',
            field=models.CharField(blank=True, help_text='Preencha se nÃ£o encontrou sua parÃ³quia na lista.', max_length=120, verbose_name='Outra parÃ³quia (texto livre)'),
        ),
        migrations.AddField(
            model_name='inscricaoservos',
            name='outra_paroquia',
            field=models.CharField(blank=True, help_text='Preencha se nÃ£o encontrou sua parÃ³quia na lista.', max_length=120, verbose_name='Outra parÃ³quia (texto livre)'),
        ),
        migrations.AlterField(
            model_name='alocacaoministerio',
            name='funcao',
            field=models.CharField(blank=True, help_text='Ex.: CoordenaÃ§Ã£o, Liturgia, MÃºsica...', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alocacaoministerio',
            name='inscricao',
            field=models.OneToOneField(help_text='A inscriÃ§Ã£o deste servo (no evento de Servos).', on_delete=django.db.models.deletion.CASCADE, related_name='alocacao_ministerio', to='inscricoes.inscricao'),
        ),
        migrations.AlterField(
            model_name='alocacaoministerio',
            name='is_coordenador',
            field=models.BooleanField(default=False, verbose_name='Ã‰ coordenador(a) do ministÃ©rio?'),
        ),
        migrations.AlterField(
            model_name='conjuge',
            name='conjuge_inscrito',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], default='nao', max_length=3, verbose_name='CÃ´njuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='conjuge',
            name='ja_e_campista',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], default='nao', max_length=3, verbose_name='JÃ¡ Ã© Campista?'),
        ),
        migrations.AlterField(
            model_name='conjuge',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do CÃ´njuge'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='grau_parentesco',
            field=models.CharField(choices=[('mae', 'MÃ£e'), ('pai', 'Pai'), ('irmao', 'IrmÃ£o'), ('tio', 'Tio'), ('tia', 'Tia'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventoacampamento',
            name='evento_relacionado',
            field=models.ForeignKey(blank=True, help_text='Se este for um evento de Servos, vincule ao evento principal em que irÃ£o servir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_servos', to='inscricoes.eventoacampamento'),
        ),
        migrations.AlterField(
            model_name='eventoacampamento',
            name='permitir_inscricao_servos',
            field=models.BooleanField(default=False, help_text='Se marcado, o evento de Servos vinculado pode receber inscriÃ§Ãµes.'),
        ),
        migrations.AlterField(
            model_name='eventoacampamento',
            name='tipo',
            field=models.CharField(choices=[('senior', 'Acampamento SÃªnior'), ('juvenil', 'Acampamento Juvenil'), ('mirim', 'Acampamento Mirim'), ('servos', 'Acampamento de Servos'), ('casais', 'Encontro de Casais'), ('evento', 'Evento'), ('retiro', 'Retiro'), ('pagamento', 'Pagamento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventoacampamento',
            name='valor_inscricao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor da InscriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='filho',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='cor_nome',
            field=models.CharField(choices=[('Amarelo', 'Amarelo'), ('Vermelho', 'Vermelho'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Laranja', 'Laranja'), ('Roxo', 'Roxo'), ('Rosa', 'Rosa'), ('Ciano', 'Ciano'), ('Lima', 'Lima'), ('Cinza', 'Cinza')], default='Amarelo', help_text='Nome da cor do catÃ¡logo (ex.: Amarelo, Vermelho, Azul...)', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='cpf_conjuge',
            field=models.CharField(blank=True, help_text='CPF do cÃ´njuge (com ou sem mÃ¡scara)', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='inscricao_pareada',
            field=models.OneToOneField(blank=True, help_text='Outra inscriÃ§Ã£o (cÃ´njuge) vinculada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareada_por', to='inscricoes.inscricao'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ja_e_campista',
            field=models.BooleanField(default=False, verbose_name='JÃ¡ Ã© campista?'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviada'), ('under_review', 'Em anÃ¡lise'), ('approved', 'Aprovada'), ('waitlist', 'Lista de espera'), ('rejected', 'Rejeitada'), ('selected', 'Selecionada/Convocada'), ('pay_pending', 'Pagamento pendente'), ('pay_confirmed', 'Pagamento confirmado'), ('cancel_user', 'Cancelada pelo usuÃ¡rio'), ('cancel_admin', 'Cancelada pela parÃ³quia'), ('refund_req', 'Reembolso solicitado'), ('refund_ok', 'Reembolso aprovado'), ('refund_den', 'Reembolso negado')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Ã‰ batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=10, null=True, verbose_name='Casado no religioso?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='CÃ´njuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui Diabetes?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'ViÃºvo(a)'), ('uniao_estavel', 'UniÃ£o EstÃ¡vel')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='foto_casal',
            field=models.ImageField(blank=True, null=True, upload_to='casais/fotos/'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='InformaÃ§Ãµes extras'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='InscriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui limitaÃ§Ãµes fÃ\xadsicas ou mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do CÃ´njuge'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='ParÃ³quia'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui PressÃ£o Alta?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui algum problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitaÃ§Ã£o/mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='tempo_casado_uniao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo de uniÃ£o'),
        ),
        migrations.AlterField(
            model_name='inscricaocasais',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'NÃ£o sei')], max_length=3, null=True, verbose_name='Tipo SanguÃ\xadneo'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Ã‰ batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='CÃ´njuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui Diabetes?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'ViÃºvo(a)'), ('uniao_estavel', 'UniÃ£o EstÃ¡vel')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='InformaÃ§Ãµes extras'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='InscriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui limitaÃ§Ãµes fÃ\xadsicas ou mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do CÃ´njuge'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='ParÃ³quia'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui PressÃ£o Alta?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui algum problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitaÃ§Ã£o/mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='tempo_casado_uniao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HÃ¡ quanto tempo sÃ£o casados/estÃ£o em uniÃ£o estÃ¡vel?'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'NÃ£o sei')], max_length=3, null=True, verbose_name='Tipo SanguÃ\xadneo'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Ã‰ batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='CÃ´njuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui Diabetes?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'ViÃºvo(a)'), ('uniao_estavel', 'UniÃ£o EstÃ¡vel')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='InformaÃ§Ãµes extras'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='InscriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui limitaÃ§Ãµes fÃ\xadsicas ou mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do CÃ´njuge'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='ParÃ³quia'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui PressÃ£o Alta?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui algum problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitaÃ§Ã£o/mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='tempo_casado_uniao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HÃ¡ quanto tempo sÃ£o casados/estÃ£o em uniÃ£o estÃ¡vel?'),
        ),
        migrations.AlterField(
            model_name='inscricaojuvenil',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'NÃ£o sei')], max_length=3, null=True, verbose_name='Tipo SanguÃ\xadneo'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Ã‰ batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='CÃ´njuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui Diabetes?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'ViÃºvo(a)'), ('uniao_estavel', 'UniÃ£o EstÃ¡vel')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='InformaÃ§Ãµes extras'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='InscriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui limitaÃ§Ãµes fÃ\xadsicas ou mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do CÃ´njuge'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='ParÃ³quia'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui PressÃ£o Alta?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui algum problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitaÃ§Ã£o/mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='tempo_casado_uniao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HÃ¡ quanto tempo sÃ£o casados/estÃ£o em uniÃ£o estÃ¡vel?'),
        ),
        migrations.AlterField(
            model_name='inscricaomirim',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'NÃ£o sei')], max_length=3, null=True, verbose_name='Tipo SanguÃ\xadneo'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Ã‰ batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='CÃ´njuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui Diabetes?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'ViÃºvo(a)'), ('uniao_estavel', 'UniÃ£o EstÃ¡vel')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='InformaÃ§Ãµes extras'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='InscriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui limitaÃ§Ãµes fÃ\xadsicas ou mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do CÃ´njuge'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='ParÃ³quia'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui PressÃ£o Alta?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui algum problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitaÃ§Ã£o/mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='tempo_casado_uniao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HÃ¡ quanto tempo sÃ£o casados/estÃ£o em uniÃ£o estÃ¡vel?'),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'NÃ£o sei')], max_length=3, null=True, verbose_name='Tipo SanguÃ\xadneo'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Ã‰ batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='CÃ´njuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui Diabetes?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'ViÃºvo(a)'), ('uniao_estavel', 'UniÃ£o EstÃ¡vel')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='InformaÃ§Ãµes extras'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='InscriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui limitaÃ§Ãµes fÃ\xadsicas ou mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do CÃ´njuge'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='ParÃ³quia'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui PressÃ£o Alta?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui algum problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitaÃ§Ã£o/mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='tempo_casado_uniao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HÃ¡ quanto tempo sÃ£o casados/estÃ£o em uniÃ£o estÃ¡vel?'),
        ),
        migrations.AlterField(
            model_name='inscricaosenior',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'NÃ£o sei')], max_length=3, null=True, verbose_name='Tipo SanguÃ\xadneo'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='alergia_alimento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum alimento?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='alergia_medicamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui alergia a algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='batizado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Ã‰ batizado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='casado_na_igreja',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Casado na Igreja?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='conjuge_inscrito',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='CÃ´njuge Inscrito?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='crismado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Crismado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui Diabetes?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='dizimista',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Dizimista?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'ViÃºvo(a)'), ('uniao_estavel', 'UniÃ£o EstÃ¡vel')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='informacoes_extras',
            field=models.TextField(blank=True, null=True, verbose_name='InformaÃ§Ãµes extras'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao', verbose_name='InscriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='medicamento_controlado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Usa algum medicamento controlado?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='mobilidade_reduzida',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui limitaÃ§Ãµes fÃ\xadsicas ou mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do CÃ´njuge'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='paroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.paroquia', verbose_name='ParÃ³quia'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='pressao_alta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui PressÃ£o Alta?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='problema_saude',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'NÃ£o')], max_length=3, null=True, verbose_name='Possui algum problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='protocolo_administracao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Protocolo de administraÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='qual_mobilidade_reduzida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual limitaÃ§Ã£o/mobilidade reduzida?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='qual_problema_saude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual problema de saÃºde?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='tempo_casado_uniao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HÃ¡ quanto tempo sÃ£o casados/estÃ£o em uniÃ£o estÃ¡vel?'),
        ),
        migrations.AlterField(
            model_name='inscricaoservos',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('NS', 'NÃ£o sei')], max_length=3, null=True, verbose_name='Tipo SanguÃ\xadneo'),
        ),
        migrations.AlterField(
            model_name='leadlanding',
            name='whatsapp',
            field=models.CharField(help_text='WhatsApp em E.164 BR: +55DDDNÃšMERO (ex.: +5563920013103)', max_length=20, validators=[django.core.validators.RegexValidator(message='Use +55 seguido de 10 ou 11 dÃ\xadgitos (ex.: +5563920013103).', regex='^\\+55\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='mercadopagoconfig',
            name='taxa_pix_fixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor fixo por transaÃ§Ã£o PIX', max_digits=8),
        ),
        migrations.AlterField(
            model_name='mercadopagoownerconfig',
            name='email_cobranca',
            field=models.EmailField(blank=True, help_text='E-mail que aparecerÃ¡ como pagador padrÃ£o', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mercadopagoownerconfig',
            name='notificacao_webhook_url',
            field=models.URLField(blank=True, help_text='Opcional: URL pÃºblica do webhook de repasses', null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('pix', 'Pix'), ('credito', 'CartÃ£o de CrÃ©dito'), ('debito', 'CartÃ£o de DÃ©bito'), ('dinheiro', 'Dinheiro')], default='pix', max_length=20),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo da ParÃ³quia'),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='repasse_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Percentual aplicado por padrÃ£o sobre o lÃ\xadquido arrecadado.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual de Repasse ao Dono (%)'),
        ),
        migrations.AlterField(
            model_name='paroquia',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone no formato E.164 BR: +55DDDNÃšMERO (ex.: +5563920013103)', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato invÃ¡lido. Use +55 seguido de 10 ou 11 dÃ\xadgitos (ex.: +5563920013103).', regex='^\\+55\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='participante',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='numero',
            field=models.CharField(max_length=30, verbose_name='NÃºmero'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EndereÃ§o'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='imagem_ajuda',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem da Ajuda (botÃ£o flutuante)'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='imagem_insc',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagem exibida nas telas de inscriÃ§Ã£o (opcional).', max_length=255, null=True, verbose_name='Imagem da InscriÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='imagem_pagto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem do Pagamento (PIX / instruÃ§Ãµes)'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NÃºmero'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='telefone_contato',
            field=models.CharField(blank=True, help_text='Use +55DDDNÃšMERO (ex.: +5563920013103)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato invÃ¡lido. Use +55 seguido de 10 ou 11 dÃ\xadgitos (ex.: +5563920013103).', regex='^\\+55\\d{10,11}$')], verbose_name='Telefone de Contato (E.164 BR)'),
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='texto',
            field=models.TextField(verbose_name='Texto da PolÃ\xadtica de Privacidade'),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='contato_whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp em E.164 (ex.: +5563920013103).', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Use +55 seguido de 10 ou 11 dÃ\xadgitos.', regex='^\\+55\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='descricao',
            field=models.TextField(blank=True, help_text='Detalhe as regras (ex.: Integral atÃ© 7 dias antes; apÃ³s isso, 70%).'),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='evento',
            field=models.OneToOneField(help_text='Cada evento pode ter (no mÃ¡ximo) uma polÃ\xadtica de reembolso.', on_delete=django.db.models.deletion.CASCADE, related_name='politica_reembolso', to='inscricoes.eventoacampamento'),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='permite_reembolso',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o evento nÃ£o aceitarÃ¡ solicitaÃ§Ãµes de reembolso.'),
        ),
        migrations.AlterField(
            model_name='politicareembolso',
            name='prazo_solicitacao_dias',
            field=models.PositiveIntegerField(default=7, help_text='Dias ANTES do inÃ\xadcio do evento para solicitar reembolso.'),
        ),
        migrations.AlterField(
            model_name='preferenciascomunicacao',
            name='whatsapp_optin_fonte',
            field=models.CharField(choices=[('form', 'FormulÃ¡rio/Portal'), ('admin', 'Admin'), ('import', 'ImportaÃ§Ã£o')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='categoria',
            field=models.CharField(choices=[('hero', 'Hero / Capa'), ('screenshot', 'Screenshot'), ('logo', 'Logo/Marca'), ('ilustracao', 'IlustraÃ§Ã£o'), ('icone', 'ÃƒÂ\x8dcone'), ('banner', 'Banner'), ('outro', 'Outro')], default='screenshot', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='creditos',
            field=models.CharField(blank=True, max_length=200, verbose_name='CrÃ©ditos (opcional)'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='key',
            field=models.SlugField(help_text='Ex.: dashboard, pagamentos, questionario-pronto', max_length=80, unique=True, verbose_name='Chave Ãºnica'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='titulo',
            field=models.CharField(blank=True, max_length=120, verbose_name='TÃ\xadtulo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin_geral', 'Administrador Geral'), ('admin_paroquia', 'Administrador da ParÃ³quia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='videoeventoacampamento',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='VÃ\xaddeo do Evento'),
        ),
    ]
